# This workflow is used to run all dbt tests

name: Run all dbt tests

on:
  pull_request:
    types: ['closed']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout this repo in order to access profiles.yml
      - name: log stuff
      
        run:
          echo pr merged ${{ github.event.pull_request.merged }}
