# This workflow is used to run all dbt tests

name: Run all dbt tests

on:
  push:
  pull_request:
    types: ['closed']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout this repo in order to access profiles.yml
      - name: log stuff
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
